### ISSUE TITLE
Hay archivos que no deberían estar versionados

### ISSUE THREAD

**Issue by sergio-ic** [BarraSantiago/MoonPatrol#1]
Revisar que hay archivos que no deberían estar versionados:
![imagen](https://user-images.githubusercontent.com/17152612/199249172-f275c7a0-f74e-4366-90c6-c12ba922dc09.png)

**Comment by BarraSantiago** [comment]
Gracias, ahí los borre, excepto el .idea que contiene el gitignore y otros archivos de jetbrains Raider
